export const Users = [
  {
    id: 1,
    profilePicture: "assets/brendan.jpeg",
    username: "Brendan Eich",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "assets/images/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    photo: "assets/post/1.png",
    date: "5 mins ago",
    desc: "Enjoy easy reconciliation of payments while giving your customers the freedom to pay from any mobile wallet. From Equitel, MPESA, Airtel Money ama Equity Mobile App, the One Equity Till Number is the payment partner for you. Get One Equity Till Number yako leo https://bit.ly/3rxcZNR ​",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.png",
    desc: "Unachapa biz online ama offline? Streamline your payment process and take your business to the next level with the ONE Equity Till Number. Get yourself one for free today https://bit.ly/3rxcZNR #KulipwaNiRahisi",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    photo: "assets/post/3.png",
    desc: "As you enjoy the convenience of online banking and online shopping, here are a few safety practices to safeguard your account. ​​#KaaChonjo #KataaUtapeli",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.png",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    desc: "The Equity Volleyball, Football and Basketball teams will be competing against various teams from the 10th of March 2023 to the 12th of March 2023. Join us to cheer them during the matches. #EquitySports",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    desc: "Equity Hawks shooting guard Melissa Akinyi (centre) who had 11 points powers her way through the opposing players’ contact. Equity Hawks are currently leading the standings with 34 points from 18 games played so far. #EquitySports #Basketball",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    photo: "assets/post/7.jpg",
    desc: "Equity Squash team during the Impala Sports Squash Tournament. Teresa Okoth (3rd left) emerged Bronze winner in the women’s plate. #EquitySports #Squash",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    desc: "This International Women's Day 2023, remember that despite the barriers you may face, the power to thrive lies in you.​ Keep breaking the ceiling by embracing the #PowerWithinYou and forging a mindset of excellence in pursuit of your life goals. #EmbraceEquity",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    photo: "assets/post/9.jpg",
    desc: "Prof. Stephen J. Anderson of Marketing at McCombs School of Business gives remarks at Equity where he accompanied MBA students from The University of Texas on a study tour. #Education #Research",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    desc: "Equity Group Managing Director and CEO Dr James Mwangi (centre, front row), Prof. Stephen J. Anderson of Marketing at McCombs School of Business (3rd left, front row) and MBA students from The University of Texas University take a photo during their study tour to Equity. ",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
